name: Check Markdown links

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'
  schedule:
    - cron: '0 0 1 * *'  # Run monthly

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/mlc_config.json'
        folder-path: '.'
        max-depth: -1