name: Markdown Lint

on: [push]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install -g markdownlint-cli
    - run: markdownlint '**/*.md' --ignore node_modules